### ISSUE TITLE
Add a new pod/container

### ISSUE THREAD

**Issue by fatango** [ct-Open-Source/team-container#18]
The prebuild pods are working on my server, i want to add a new pod ([collabora](https://nextcloud.com/collaboraonline/)) to edit documents in nextcloud. There are many documentations how to achieve this in a docker setup. Team-Container installs new pods with _helm_ but i don't understand the configuration in 7+ different yaml-files.
The ports need to be set (for traefik?)?
How/where does traefik get/knows the new subdomain for the certificate?

[Install Collabora with docker](https://www.collaboraoffice.com/code/docker/)
[Helm Collabora-Code](https://github.com/helm/charts/tree/master/stable/collabora-code)

How can i add/configure a new pod to the existing ones?

**Comment by sirrus** [comment]
You need to have a team-collabora folder containing the yaml files.
Traeffik will be involved with a team-collabora/templates/05-ingress.yaml with this content:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "team-colabora.fullname" . }}-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.app.name }}.{{ .Values.app.domain }}`)
      kind: Rule
      priority: 100
      services:
        - name: {{ include "team-colabora.fullname" . }}-web
          port: 80
  tls:
    certResolver: default
```

What files should be there:
values-colabora.yaml
team-colabora/Chart.yaml
team-colabora/values.yaml
team-colabora/templates/02-service.yaml
team-colabora/templates/05-ingress.yaml
team-colabora/templates/deploy.yaml
team-colabora/templates/_helpers.yaml
