### ISSUE TITLE
nextcloud: Reverse proxy settings missing

### ISSUE THREAD

**Issue by kolewu** [ct-Open-Source/team-container#33]
The nextcloud pod misses the settings for reverse proxy and service discovery. This leads to the following warnings:
> * The reverse proxy header configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If not, this is a security issue and can allow an attacker to spoof their IP address as visible to the Nextcloud. Further information can be found in the [documentation](https://docs.nextcloud.com/server/18/go.php?to=admin-reverse-proxy).
> * Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the [documentation](https://docs.nextcloud.com/server/18/go.php?to=admin-setup-well-known-URL).
> * Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation](https://docs.nextcloud.com/server/18/go.php?to=admin-setup-well-known-URL).

I tried the following addition to `team-nextcloud/templates/05-ingress.yaml`, but was not successful:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: metadata-{{ include "team-nextcloud.fullname" . }}
spec:
  redirectRegex:
    permanent: 'true'
    regex: ^https://(.*)/.well-known/(card|cal)dav
    replacement: https://${1}/remote.php/dav/
```

With or without this configuration there is a wrong answer to the query for the well-known address:
```
$ curl https://cloud.example.org/.well-known/carddav
```
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://cloud.example.org/remote.php/dav/">here</a>.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at cloud.example.org Port 80</address>
</body></html>
```
