### ISSUE TITLE
Nextcloud service is not starting - jitsi and router seem to work fine

### ISSUE THREAD

**Issue by Wollipolli** [ct-Open-Source/team-container#48]
First of all, thanks for this awesome repo!
I have some issues with the nextcloud instance, maybe anyone with more experience can help?

I want to install a nextcloud and jitsi instance on my Zotac zbox CA621 with 16GB RAM and 265GB SSD behind a Fritzbox.
I registered 3 (free) subdomains from noip.com (*.ddns.net) and pointed them to the IP of my Fritzbox, which has a portforwarding to the zbox. I installed Ubuntu Server 20.04 LTS performed updates and cloned the repo.
I then followed the instructions and ended up having a running router and jitsi server. However the Nextcloud instance is not running. I set up name and domain as for the others, but the Let's Encrypt Cert is missing. When I open the nextcloud adress in Firefox and confirm the security exception for missing https, the page simply contains: "404 page not found".

Where could I have made a mistake?

**Comment by sirrus** [comment]
I'would suggest to start over. nextcloud didn't create it's storage containers.

Is there really enough space? Maybe a wrong LVM setup? What's the output of:

`df -h`

**Comment by Wollipolli** [comment]
Thanks! That was it.
I did not know nextcloud expects a separate pre-formatted storage partition.
I thought this would happen during the setup.

**Comment by sirrus** [comment]
You've set user auth in jitsi - but your config seems to be wrong. Please paste your config without passwords...

`Exec lifecycle hook ([/bin/bash -c sleep 60; prosodyctl --config /config/prosody.cfg.lua register meetmaster jitsisubdomain.ddns.net password]) for Container "prosody" in Pod "video-team-video-prosody-6769ff54d7-7tt8c_default(8208a497-f090-40e7-9101-25ce7aaba746)" failed - error: command '/bin/bash -c sleep 60; prosodyctl --config /config/prosody.cfg.lua register meetmaster jitsisubdomain.ddns.net password' exited with 1: , message: "Error: Account creation/modification not supported.\n`

**Comment by Wollipolli** [comment]
```
app:
  name: mysubdomain
  domain: ddns.net
  pullpolicy: IfNotPresent # set to Always for auto updates

auth:
  enabled: true
  guests: true
  # internal auth
  type: internal
  admin:
    user: myadminname
    password: "mypassword"
  # ldap auth - remove above "type: internal" auth to use it
  #type: ldap
  #ldapauthmethod: bind
  #ldapurl: ldap://LDAP_SERVER
  #ldapusetls: 1
  #ldapstarttls: 1 # needs LDAP_VERSIOn 3
  #ldaptlscacertfile:
  #ldaptlscacertdir:
  #ldaptlscheckpeer:
  #ldapbase: OU=users,DC=domain,DC=local
  #ldapbinddn: CN=ldap user,OU=svc_users,DC=domain,DC=local
  #ldapbindpw: VerySecretPassword
  #ldapfilter: (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
  #ldapversion: 3 # can break helm upgrade

logLevel: "info"
hideWelcomePage: true
# Remove following # to use different stun servers
# stun:
#  server: stun.stunprotocol.org:3478, stun.services.mozilla.com:3478

```
